# Generated by Django 3.1.5 on 2021-02-20 12:55

from django.db import migrations, models
import django.db.models.deletion
from amokryshev.utils import FileFieldDedupByName


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Locale')),
                ('picture', FileFieldDedupByName(upload_to='', verbose_name='Main photo')),
                ('intro', models.TextField(verbose_name='Introduction')),
                ('role', models.CharField(max_length=200, verbose_name='Roles & Positions')),
                ('sub_role', models.CharField(max_length=200, verbose_name='Roles explanation')),
                ('message', models.TextField(verbose_name='Inference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CvSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Locale')),
                ('pos', models.IntegerField(verbose_name='Position on page')),
                ('chapter', models.CharField(max_length=30, verbose_name='CSS cls icofont')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CvSectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(verbose_name='Position on page')),
                ('title', models.CharField(max_length=200, verbose_name='Position title')),
                ('period', models.CharField(max_length=200, verbose_name='Time period')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.cvsection')),
            ],
        ),
        migrations.CreateModel(
            name='FactsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Locale')),
                ('intro', models.TextField(verbose_name='Introduction')),
                ('finale', models.TextField(verbose_name='Inference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainMenuPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(verbose_name='Position on page')),
                ('is_active', models.BooleanField(default=False)),
                ('view', models.CharField(max_length=50, verbose_name='Name of the view')),
                ('anchor', models.CharField(max_length=50, verbose_name='Anchor on the page')),
                ('icon', models.CharField(max_length=30, verbose_name='CSS cls icofont')),
                ('text', models.CharField(max_length=50, verbose_name='The item name')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Locale')),
                ('picture', FileFieldDedupByName(upload_to='portfolio', verbose_name='Avatar_photo')),
                ('filter', models.CharField(choices=[('filter-app', 'Application'), ('filter-article', 'Article'), ('filter-other', 'Other')], default='filter-article', max_length=14, verbose_name='Chapter')),
                ('is_published', models.CharField(choices=[('Y', 'Published'), ('N', 'Hidden')], default='Y', max_length=1, verbose_name='Is published')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Locale')),
                ('intro', models.TextField(verbose_name='Introduction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Skill tag')),
                ('count', models.IntegerField(verbose_name='Count of votes')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30, verbose_name='CSS cls of the link')),
                ('href', models.CharField(max_length=200, verbose_name='the Link')),
                ('icon', models.CharField(max_length=30, verbose_name='CSS cls icofont')),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Locale')),
                ('intro', models.TextField(verbose_name='Introduction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(verbose_name='Position on page')),
                ('text', models.TextField(verbose_name='Description')),
                ('picture', FileFieldDedupByName(upload_to='testimonials', verbose_name='Persons photo')),
                ('person', models.CharField(max_length=200, verbose_name='Person')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Persons position')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.testimonialssection')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(verbose_name='Position on page')),
                ('title', models.CharField(max_length=200, verbose_name='Service title')),
                ('icon', models.CharField(max_length=30, verbose_name='CSS cls icofont')),
                ('href', models.CharField(blank=True, max_length=200, verbose_name='External link')),
                ('description', models.TextField(verbose_name='Description')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.servicessection')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSectionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50, verbose_name='On hover text tip')),
                ('icon', models.CharField(max_length=30, verbose_name='CSS cls icofont')),
                ('view', models.CharField(blank=True, max_length=50, verbose_name='Name of the view')),
                ('anchor', models.CharField(blank=True, max_length=50, verbose_name='Anchor on the page')),
                ('href', models.CharField(blank=True, max_length=200, verbose_name='External link')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.portfoliosection')),
            ],
        ),
        migrations.CreateModel(
            name='FactsSectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(verbose_name='Position on page')),
                ('icon', models.CharField(max_length=30, verbose_name='CSS cls icofont')),
                ('years', models.IntegerField(verbose_name='Years count')),
                ('branch', models.CharField(max_length=50, verbose_name='Sector')),
                ('details', models.CharField(max_length=200, verbose_name='Extra info')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.factssection')),
            ],
        ),
        migrations.CreateModel(
            name='CvSectionItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(verbose_name='Position on page')),
                ('text', models.CharField(max_length=250, verbose_name='The item name')),
                ('href', models.CharField(blank=True, max_length=200, verbose_name='External link')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.cvsectionitem')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.cvsectionitemdetail')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSectionFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_num', models.CharField(choices=[('F', 'First'), ('S', 'Second')], max_length=1, verbose_name='Number of list')),
                ('key', models.CharField(max_length=20, verbose_name='Name of the point')),
                ('value', models.CharField(max_length=200, verbose_name='Text of the point')),
                ('href', models.CharField(blank=True, max_length=200, verbose_name='Link of the point')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.aboutsection')),
            ],
        ),
    ]
