# Generated by Django 3.1.5 on 2021-03-09 18:32

import amokryshev.utils.dedup_file_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20210219_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsection',
            name='chapter',
            field=models.CharField(max_length=30, verbose_name='Chapter'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=2, verbose_name='Locale')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('tags', models.CharField(blank=True, max_length=120, verbose_name='Tags')),
                ('slug', models.CharField(max_length=160, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='Summary')),
                ('picture', amokryshev.utils.dedup_file_field.FileFieldDedupByName(upload_to='portfolio', verbose_name='Avatar_photo')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_published', models.CharField(choices=[('Y', 'Published'), ('N', 'Hidden')], default='Y', max_length=1, verbose_name='Is published')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('author', models.CharField(blank=True, max_length=160, verbose_name='Author')),
                ('author_link', models.CharField(blank=True, max_length=250, verbose_name='Author link')),
                ('source', models.CharField(blank=True, max_length=160, verbose_name='Source')),
                ('source_link', models.CharField(blank=True, max_length=250, verbose_name='Source link')),
                ('related', models.ManyToManyField(blank=True, related_name='_article_related_+', to='mainsite.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
