version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  cache:
    image: redis
    ports:
      - "6379:6379"